name: Hello World

on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Say Hello World
      run: echo "Hello World"
